/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.runner.JUnitCore;

public class AppTest {
    public void main(String[] args) {
        JUnitCore.main("springbook.user.daoUserDaoTest");
    }
}
